// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbowhmjtmknkfhtqlqpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtib3dobWp0bWtua2ZodHFscXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMDYxMDIsImV4cCI6MjA2MTU4MjEwMn0.cQEkBL_WPzLRaUdG9Q3QKh4_u6qPzzxGIOVq9cXlOZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);